export const GET_TOPICS_BY_PARENT_ID = 'GET_TOPICS_BY_PARENT_ID';
export const GET_TOPICS_BY_PARENT_ID_SUCCESS =
  'GET_TOPICS_BY_PARENT_ID_SUCCESS';
export const GET_TOPICS_BY_PARENT_ID_FAILURE =
  'GET_TOPICS_BY_PARENT_ID_FAILURE';

export const GET_TOPIC_BY_ID = 'GET_TOPIC_BY_ID';
export const GET_TOPIC_BY_ID_SUCCESS = 'GET_TOPIC_BY_ID_SUCCESS';
export const GET_TOPIC_BY_ID_FAILURE = 'GET_TOPIC_BY_ID_FAILURE';

export const GET_CARDS_BY_IDS = 'GET_CARDS_BY_IDS';
export const GET_CARDS_BY_IDS_SUCCESS = 'GET_CARDS_BY_IDS_SUCCESS';
export const GET_CARDS_BY_IDS_FAILURE = 'GET_CARDS_BY_IDS_FAILURE';

export const GET_CARDS_PROGRESS = 'GET_CARDS_PROGRESS';
export const GET_CARDS_PROGRESS_SUCCESS = 'GET_CARDS_PROGRESS_SUCCESS';
export const GET_CARDS_PROGRESS_FAILURE = 'GET_CARDS_PROGRESS_FAILURE';

export const GET_CARDS_BY_PARENT_ID = 'GET_CARDS_BY_PARENT_ID';
export const GET_CARDS_BY_PARENT_ID_SUCCESS = 'GET_CARDS_BY_PARENT_ID_SUCCESS';
export const GET_CARDS_BY_PARENT_ID_FAILURE = 'GET_CARDS_BY_PARENT_ID_FAILURE';

export const GAME_UPDATE_LIST_GAME = 'GAME_UPDATE_LIST_GAME';
export const GAME_LOAD_GAME = 'GAME_LOAD_GAME';
export const START_NEW_TEST = 'START_NEW_TEST';

export const GAME_LOAD_STUDY_GAME = 'GAME_LOAD_STUDY_GAME';
export const GAME_ON_CONTINUE = 'GAME_ON_CONTINUE';
export const GAME_ON_SELECTED_CHOICE = 'GAME_ON_SELECTED_CHOICE';
export const GAME_ON_CAL_PROGRESS = 'GAME_ON_CAL_PROGRESS';
export const GAME_ON_CHOICE_SELECTED = 'GAME_ON_CHOICE_SELECTED';
export const START_NEW_GAME = 'START_NEW_GAME';
export const RESUME_GAME = 'RESUME_GAME';
export const REMOVE_GAME = 'REMOVE_GAME';
export const GAME_END_GAME = 'GAME_END_GAME';

export const LOAD_TEST_SETTING_BY_TOPIC_ID = 'LOAD_TEST_SETTING_BY_TOPIC_ID';
export const SAVE_NEW_TEST_SETTING = 'SAVE_NEW_TEST_SETTING';
export const UPDATE_TEST_SETTING = 'UPDATE_TEST_SETTING';

export const UPDATE_QUESTION_PROGRESS = 'UPDATE_QUESTION_PROGRESS';

export const GET_QUESTION_PROGRESS_BY_IDS = 'GET_QUESTION_PROGRESS_BY_IDS';
export const GET_QUESTION_PROGRESS_BY_IDS_SUCCESS =
  'GET_QUESTION_PROGRESS_BY_IDS_SUCCESS';
export const GET_QUESTION_PROGRESS_BY_IDS_FAILURE =
  'GET_QUESTION_PROGRESS_BY_IDS_FAILURE';

export const GET_TOPICS_PROGRESS_BY_TOPIC_IDS =
  'GET_TOPICS_PROGRESS_BY_TOPIC_IDS';
export const GET_TOPICS_PROGRESS_BY_TOPIC_IDS_SUCCESS =
  'GET_TOPICS_PROGRESS_BY_TOPIC_IDS_SUCCESS';
export const GET_TOPICS_PROGRESS_BY_TOPIC_IDS_FAILURE =
  'GET_TOPICS_PROGRESS_BY_TOPIC_IDS_FAILURE';

export const UPDATE_TOPICS_PROGRESS = 'UPDATE_TOPICS_PROGRESS';
export const UPDATE_TOPICS_PROGRESS_SUCCESS = 'UPDATE_TOPICS_PROGRESS_SUCCESS';

export const CALCULAR_TOPICS_PROGRESS = 'CALCULAR_TOPICS_PROGRESS';
export const CALCULAR_PARENT_TOPICS_PROGRESS =
  'CALCULAR_PARENT_TOPICS_PROGRESS';

export const RESET_CARD_IN_TOPIC = 'RESET_CARD_IN_TOPIC';
export const RESET_TOPIC_PROGRESS = 'RESET_TOPIC_PROGRESS';
export const PLAY_TOPIC = 'PLAY_TOPIC';
export const UNLOCK_TOPIC = 'UNLOCK_TOPIC';

export const SHOW_IMAGE_DIALOG = 'SHOW_IMAGE_DIALOG';
export const SHOW_ALERT = 'SHOW_ALERT';

export const GET_APP_INFO = 'GET_APP_INFO';
export const GET_APP_INFO_SUCCESS = 'GET_APP_INFO_SUCCESS';
export const GET_APP_INFO_FAILURE = 'GET_APP_INFO_FAILURE';

export const GET_ALL_APP_INFO = 'GET_ALL_APP_INFO';
export const GET_ALL_APP_INFO_SUCCESS = 'GET_ALL_APP_INFO_SUCCESS';
export const GET_ALL_APP_INFO_FAILURE = 'GET_ALL_APP_INFO_FAILURE';

export const GET_STATE_INFO = 'GET_STATE_INFO';
export const GET_STATE_INFO_SUCCESS = 'GET_STATE_INFO_SUCCESS';
export const GET_STATE_INFO_FAILURE = 'GET_STATE_INFO_FAILURE';

export const SET_CURRENT_STATE_INFO = 'SET_CURRENT_STATE_INFO';

export const GET_USER_RATES = 'GET_USER_RATES';
export const GET_USER_RATES_SUCCESS = 'GET_USER_RATES_SUCCESS';
export const GET_USER_RATES_FAILURE = 'GET_USER_RATES_FAILURE';

export const GET_USER_RATES_PERFECTEST = 'GET_USER_RATES_PERFECTEST';
export const GET_USER_RATES_PERFECTEST_SUCCESS =
  'GET_USER_RATES_PERFECTEST_SUCCESS';
export const GET_USER_RATES_PERFECTEST_FAILURE =
  'GET_USER_RATES_PERFECTEST_FAILURE';

export const COURSE_FETCH_BY_CATEGORY_ID = 'COURSE_FETCH_BY_CATEGORY_ID';
export const COURSE_FETCH_BY_COURSE_ID = 'COURSE_FETCH_BY_COURSE_ID';
export const COURSE_SET_DATA = 'COURSE_SET_DATA';
export const COURSE_SET_CURRENT_DATA = 'COURSE_SET_CURRENT_DATA';
export const COURSE_FETCH_SUCCESS = 'COURSE_FETCH_SUCCESS';
export const COURSE_FETCH_ON_PROGRESS = 'COURSE_FETCH_ON_PROGRESS';
export const COURSE_FETCH_FAILURE = 'COURSE_FETCH_FAILURE';

export const CATEGORY_FETCH_ALL = 'CATEGORY_FETCH_ALL';
export const CATEGORY_FETCH_BY_ID = 'CATEGORY_FETCH_BY_ID';
export const CATEGORY_SET_DATA = 'CATEGORY_SET_DATA';
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORY_FETCH_FAILURE = 'CATEGORY_FETCH_FAILURE';
export const CATEGORY_FETCH_ON_PROGRESS = 'CATEGORY_FETCH_ON_PROGRESS';

export const TOPIC_FETCH_LARGE_BY_PARENT_ID = 'TOPIC_FETCH_LARGE_BY_PARENT_ID';
export const TOPIC_FETCH_SMALL_BY_PARENT_ID = 'TOPIC_FETCH_SMALL_BY_PARENT_ID';
export const TOPIC_FETCH_LARGE_BY_TOPIC_ID = 'TOPIC_FETCH_LARGE_BY_TOPIC_ID';
export const TOPIC_FETCH_SMALL_BY_TOPIC_ID = 'TOPIC_FETCH_SMALL_BY_TOPIC_ID';
export const TOPIC_SET_LARGE_DATA = 'TOPIC_SET_LARGE_DATA';
export const TOPIC_SET_SMALL_DATA = 'TOPIC_SET_SMALL_DATA';
export const TOPIC_FETCH_LARGE_SUCCESS = 'TOPIC_FETCH_LARGE_SUCCESS';
export const TOPIC_FETCH_LARGE_ON_PROGRESS = 'TOPIC_FETCH_LARGE_ON_PROGRESS';
export const TOPIC_FETCH_SMALL_SUCCESS = 'TOPIC_FETCH_SMALL_SUCCESS';
export const TOPIC_FETCH_SMALL_ON_PROGRESS = 'TOPIC_FETCH_SMALL_ON_PROGRESS';
export const TOPIC_FETCH_FAILURE = 'TOPIC_FETCH_FAILURE';
export const TOPIC_SET_LARGE_CURRENT = 'TOPIC_SET_LARGE_CURRENT';
export const TOPIC_SET_SMALL_CURRENT = 'TOPIC_SET_SMALL_CURRENT';

export const LESSON_SET_DATA = 'LESSON_SET_DATA';
export const LESSON_FETCH_SUCCESS = 'LESSON_FETCH_SUCCESS';
export const LESSON_FETCH_ON_PROGRESS = 'LESSON_FETCH_ON_PROGRESS';
export const LESSON_SET_CURRENT = 'LESSON_SET_CURRENT';

export const ASSIGNMENT_SET_DATA = 'ASSIGNMENT_SET_DATA';
export const ASSIGNMENT_FETCH_SUCCESS = 'ASSIGNMENT_FETCH_SUCCESS';
export const ASSIGNMENT_FETCH_ON_PROGRESS = 'ASSIGNMENT_FETCH_ON_PROGRESS';

export const AUTH_LOGIN = 'AUTH_LOGIN';

export const REFERENCE_FETCH_BY_PARENT_ID = 'REFERENCE_FETCH_BY_PARENT_ID';
export const REFERENCE_FETCH_BY_COURSE_ID = 'REFERENCE_FETC_BY_COURSE_ID';
export const REFERENCE_FETCH_ON_PROGRESS = 'REFERENCE_FETCH_ON_PROGRESS';
export const REFERENCE_FETCH_SUCCESS = 'REFERENCE_FETCH_SUCCESS';
export const REFERENCE_SET_DATA = 'REFERENCE_SET_DATA';

export const OPERATION_FETCH_DATA_IN_LESSON_PAGE =
  'OPERATION_FETCH_DATA_IN_LESSON_PAGE';
