export const COURSE_FETCH_BY_CATEGORY_ID = 'COURSE_FETCH_BY_CATEGORY_ID';
export const COURSE_FETCH_ALL = 'COURSE_FETCH_ALL';
export const COURSE_FETCH_BY_USER_ID = 'COURSE_FETCH_BY_USER_ID';
export const COURSE_SET_DATA = 'COURSE_SET_DATA';
export const COURSE_SET_CURRENT_DATA = 'COURSE_SET_CURRENT_DATA';
export const COURSE_FETCH_SUCCESS = 'COURSE_FETCH_SUCCESS';
export const COURSE_FETCH_ON_PROGRESS = 'COURSE_FETCH_ON_PROGRESS';
export const COURSE_FETCH_FAILURE = 'COURSE_FETCH_FAILURE';
export const COURSE_UPDATE_DATA = 'COURSE_UPDATE_DATA';

export const CATEGORY_FETCH_ALL = 'CATEGORY_FETCH_ALL';
export const CATEGORY_FETCH_BY_ID = 'CATEGORY_FETCH_BY_ID';
export const CATEGORY_SET_DATA = 'CATEGORY_SET_DATA';
export const CATEGORY_SET_CURRENT = 'CATEGORY_SET_CURRENT';
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORY_FETCH_FAILURE = 'CATEGORY_FETCH_FAILURE';
export const CATEGORY_FETCH_ON_PROGRESS = 'CATEGORY_FETCH_ON_PROGRESS';

export const TOPIC_FETCH_BY_COURSE_ID = 'TOPIC_FETCH_BY_COURSE_ID';
export const TOPIC_FETCH_BY_TOPIC_ID = 'TOPIC_FETCH_BY_TOPIC_ID';
export const TOPIC_SET_LARGE_DATA = 'TOPIC_SET_LARGE_DATA';
export const TOPIC_SET_SMALL_DATA = 'TOPIC_SET_SMALL_DATA';
export const TOPIC_FETCH_LARGE_ON_PROGRESS = 'TOPIC_FETCH_LARGE_ON_PROGRESS';
export const TOPIC_FETCH_SMALL_ON_PROGRESS = 'TOPIC_FETCH_SMALL_ON_PROGRESS';
export const TOPIC_FETCH_LARGE_SUCCESS = 'TOPIC_FETCH_LARGE_SUCCESS';
export const TOPIC_FETCH_SMALL_SUCCESS = 'TOPIC_FETCH_SMALL_SUCCESS';

export const LESSON_FETCH_BY_LESSON_ID = 'LESSON_FETCH_BY_LESSON_ID';
export const LESSON_SET_DATA = 'LESSON_SET_DATA';
export const LESSON_FETCH_SUCCESS = 'LESSON_FETCH_SUCCESS';
export const LESSON_FETCH_ON_PROGRESS = 'LESSON_FETCH_ON_PROGRESS';

export const ASSIGNMENT_FETCH_BY_ASSIGNMENT_ID =
  'ASSIGNMENT_FETCH_BY_ASSIGNMENT_ID';
export const ASSIGNMENT_SET_DATA = 'ASSIGNMENT_SET_DATA';
export const ASSIGNMENT_FETCH_SUCCESS = 'ASSIGNMENT_FETCH_SUCCESS';
export const ASSIGNMENT_FETCH_ON_PROGRESS = 'ASSIGNMENT_FETCH_ON_PROGRESS';
export const ASSIGNMENT_SET_PARTICIPANT_DATA =
  'ASSIGNMENT_SET_PARTICIPANT_DATA';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_ON_PROGRESS = 'AUTH_ON_PROGRESS';
export const AUTH_ON_SUCCESS = 'AUTH_ON_SUCCESS';
export const AUTH_FETCH_USER_INFO = 'AUTH_FETCH_USER_INFO';
export const AUTH_SET_AUTHENTICATE = 'AUTH_SET_AUTHENTICATE';
export const AUTH_SET_USER_INFO = 'AUTH_SET_USER_INFO';

export const TOEIC_FETCH_BY_USER_ID = 'TOEIC_FETCH_BY_USER_ID';
export const TOEIC_SET_DATA = 'TOEIC_SET_DATA';
export const TOEIC_FETCH_SUCCESS = 'TOEIC_FETCH_SUCCESS';
export const TOEIC_FETCH_ON_PROGRESS = 'TOEIC_FETCH_ON_PROGRESS';
export const TOEIC_SUBMIT_SCORE = 'TOEIC_SUBMIT_SCORE';
export const TOEIC_UPDATE_SCORE = 'TOEIC_UPDATE_SCORE';

export const SCALE_FETCH_DATA = 'SCALE_FETCH_DATA';
export const SCALE_SET_DATA = 'SCALE_SET_DATA';
export const SCALE_FETCH_ON_PROGRESS = 'SCALE_FETCH_ON_PROGRESS';
export const SCALE_FETCH_SUCCESS = 'SCALE_FETCH_SUCCESS';

export const TEST_FETCH_DATA = 'TEST_FETCH_DATA';
export const TEST_SET_DATA = 'TEST_SET_DATA';
export const TEST_FETCH_ON_PROGRESS = 'TEST_FETCH_ON_PROGRESS';
export const TEST_FETCH_SUCCESS = 'TEST_FETCH_SUCCESS';

export const SET_FETCH_DATA = 'SET_FETCH_DATA';
export const SET_FETCH_BY_ID = 'SET_FETCH_BY_ID';
export const SET_SET_DATA = 'SET_SET_DATA';
export const SET_SET_CURRENT = 'SET_SET_CURRENT';
export const SET_ADD_DATA = 'SET_ADD_DATA';
export const SET_EDIT_DATA = 'SET_EDIT_DATA';
export const SET_MODIFY_TERM = 'SET_MODIFY_TERM';
export const SET_DELETE_TERM = 'SET_DELETE_TERM';
export const SET_FETCH_ON_PROGRESS = 'SET_FETCH_ON_PROGRESS';
export const SET_FETCH_SUCCESS = 'SET_FETCH_SUCCESS';

export const LEARN_FETCH_WRITE_BY_SET_ID = 'LEARN_FETCH_WRITE_BY_SET_ID';
export const LEARN_FETCH_LISTEN_BY_SET_ID = 'LEARN_FETCH_LISTEN_BY_SET_ID';
export const LEARN_FETCH_STUDY_BY_SET_ID = 'LEARN_FETCH_STUDY_BY_SET_ID';
export const LEARN_SET_STUDY_DATA = 'LEARN_SET_STUDY_DATA';
export const LEARN_SET_WRITE_DATA = 'LEARN_SET_WRITE_DATA';
export const LEARN_UPDATE_REMEMBER = 'LEARN_UPDATE_REMEMBER';
export const LEARN_SET_LISTEN_DATA = 'LEARN_SET_LISTEN_DATA';
export const LEARN_WRITE_ANSWER = 'LEARN_WRITE_ANSWER';
export const LEARN_LISTEN_ANSWER = 'LEARN_LISTEN_ANSWER';
export const LEARN_FETCH_ON_PROGRESS = 'LEARN_FETCH_ON_PROGRESS';
export const LEARN_FETCH_SUCCESS = 'LEARN_FETCH_SUCCESS';

export const OPERATION_FETCH_DATA_IN_LESSON_PAGE =
  'OPERATION_FETCH_DATA_IN_LESSON_PAGE';
export const OPERATION_FETCH_DATA_IN_COURSE_PAGE =
  'OPERATION_FETCH_DATA_IN_COURSE_PAGE';
export const OPERATION_FETCH_DATA_IN_TOPIC_PAGE =
  'OPERATION_FETCH_DATA_IN_TOPIC_PAGE';
export const OPERATION_FETCH_DATA_IN_CATEGORY_PAGE =
  'OPERATION_FETCH_DATA_IN_CATEGORY_PAGE';
export const OPERATION_FETCH_DATA_IN_ASSIGNMENT_PAGE =
  'OPERATION_FETCH_DATA_IN_ASSIGNMENT_PAGE';
export const OPERATION_FETCH_DATA_IN_UTILITY_PAGE =
  'OPERATION_FETCH_DATA_IN_UTILITY_PAGE';
export const OPERATION_FETCH_DATA_IN_TOEIC_PAGE =
  'OPERATION_FETCH_DATA_IN_TOEIC_PAGE';
export const OPERATION_FETCH_DATA_IN_TEST_PAGE =
  'OPERATION_FETCH_DATA_IN_TEST_PAGE';
export const OPERATION_FETCH_DATA_IN_TEST_RESULT_PAGE =
  'OPERATION_FETCH_DATA_IN_TEST_RESULT_PAGE';
export const OPERATION_FETCH_DATA_IN_HOME_PAGE =
  'OPERATION_FETCH_DATA_IN_HOME_PAGE';
export const OPERATION_SUBMIT_ASSIGNMENT = 'OPERATION_SUBMIT_ASSIGNMENT';
export const OPERATION_SUBMIT_TEST = 'OPERATION_SUBMIT_TEST';
export const OPERATION_PURCHASE_COURSE = 'OPERATION_PURCHASE_COURSE';
