export const COURSE_FETCH_BY_CATEGORY_ID = 'COURSE_FETCH_BY_CATEGORY_ID';
export const COURSE_FETCH_ALL = 'COURSE_FETCH_ALL';
export const COURSE_FETCH_BY_USER_ID = 'COURSE_FETCH_BY_USER_ID';
export const COURSE_SET_DATA = 'COURSE_SET_DATA';
export const COURSE_SET_CURRENT_DATA = 'COURSE_SET_CURRENT_DATA';
export const COURSE_FETCH_SUCCESS = 'COURSE_FETCH_SUCCESS';
export const COURSE_FETCH_ON_PROGRESS = 'COURSE_FETCH_ON_PROGRESS';
export const COURSE_FETCH_FAILURE = 'COURSE_FETCH_FAILURE';

export const CATEGORY_FETCH_ALL = 'CATEGORY_FETCH_ALL';
export const CATEGORY_FETCH_BY_ID = 'CATEGORY_FETCH_BY_ID';
export const CATEGORY_SET_DATA = 'CATEGORY_SET_DATA';
export const CATEGORY_SET_CURRENT = 'CATEGORY_SET_CURRENT';
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORY_FETCH_FAILURE = 'CATEGORY_FETCH_FAILURE';
export const CATEGORY_FETCH_ON_PROGRESS = 'CATEGORY_FETCH_ON_PROGRESS';

export const TOPIC_FETCH_BY_COURSE_ID = 'TOPIC_FETCH_BY_COURSE_ID';
export const TOPIC_FETCH_BY_TOPIC_ID = 'TOPIC_FETCH_BY_TOPIC_ID';
export const TOPIC_SET_LARGE_DATA = 'TOPIC_SET_LARGE_DATA';
export const TOPIC_SET_SMALL_DATA = 'TOPIC_SET_SMALL_DATA';
export const TOPIC_FETCH_LARGE_ON_PROGRESS = 'TOPIC_FETCH_LARGE_ON_PROGRESS';
export const TOPIC_FETCH_SMALL_ON_PROGRESS = 'TOPIC_FETCH_SMALL_ON_PROGRESS';
export const TOPIC_FETCH_LARGE_SUCCESS = 'TOPIC_FETCH_LARGE_SUCCESS';
export const TOPIC_FETCH_SMALL_SUCCESS = 'TOPIC_FETCH_SMALL_SUCCESS';

export const LESSON_FETCH_BY_LESSON_ID = 'LESSON_FETCH_BY_LESSON_ID';
export const LESSON_SET_DATA = 'LESSON_SET_DATA';
export const LESSON_FETCH_SUCCESS = 'LESSON_FETCH_SUCCESS';
export const LESSON_FETCH_ON_PROGRESS = 'LESSON_FETCH_ON_PROGRESS';

export const ASSIGNMENT_SET_DATA = 'ASSIGNMENT_SET_DATA';
export const ASSIGNMENT_FETCH_SUCCESS = 'ASSIGNMENT_FETCH_SUCCESS';
export const ASSIGNMENT_FETCH_ON_PROGRESS = 'ASSIGNMENT_FETCH_ON_PROGRESS';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_ON_PROGRESS = 'AUTH_ON_PROGRESS';
export const AUTH_ON_SUCCESS = 'AUTH_ON_SUCCESS';
export const AUTH_FETCH_USER_INFO = 'AUTH_FETCH_USER_INFO';
export const AUTH_SET_AUTHENTICATE = 'AUTH_SET_AUTHENTICATE';
export const AUTH_SET_USER_INFO = 'AUTH_SET_USER_INFO';

export const OPERATION_FETCH_DATA_IN_LESSON_PAGE =
  'OPERATION_FETCH_DATA_IN_LESSON_PAGE';
export const OPERATION_FETCH_DATA_IN_COURSE_PAGE =
  'OPERATION_FETCH_DATA_IN_COURSE_PAGE';
export const OPERATION_FETCH_DATA_IN_TOPIC_PAGE =
  'OPERATION_FETCH_DATA_IN_TOPIC_PAGE';
export const OPERATION_FETCH_DATA_IN_CATEGORY_PAGE =
  'OPERATION_FETCH_DATA_IN_CATEGORY_PAGE';
